name: Encrypt 77 JSON 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        echo '{}' > package.json
        npm install

    - name: Create encryption script
      run: |
        cat << 'EOF' > encrypt.js
        const fs = require('fs');
        const key = 'mysecretkey';
        const XORCipher = (input, key) => {
          let output = '';
          for (let i = 0; i < input.length; i++) {
            output += String.fromCharCode(input.charCodeAt(i) ^ key.charCodeAt(i % key.length));
          }
          return output;
        };
        const data = JSON.parse(fs.readFileSync('77.json', 'utf8'));
        const encryptSection = (section) => section.map(user => XORCipher(user, key));
        if (data.WorldPermissionLevels) {
          if (data.WorldPermissionLevels.Staff) data.WorldPermissionLevels.Staff = encryptSection(data.WorldPermissionLevels.Staff);
          if (data.WorldPermissionLevels.Whale) data.WorldPermissionLevels.Whale = encryptSection(data.WorldPermissionLevels.Whale);
          if (data.WorldPermissionLevels.Hero) data.WorldPermissionLevels.Hero = encryptSection(data.WorldPermissionLevels.Hero);
          if (data.WorldPermissionLevels.Supporter) data.WorldPermissionLevels.Supporter = encryptSection(data.WorldPermissionLevels.Supporter);
          if (data.WorldPermissionLevels.Homie) data.WorldPermissionLevels.Homie = encryptSection(data.WorldPermissionLevels.Homie);
          if (data.WorldPermissionLevels.VIP) data.WorldPermissionLevels.VIP = encryptSection(data.WorldPermissionLevels.VIP);
        }
        fs.mkdirSync('docs', { recursive: true });
        fs.writeFileSync('docs/encrypted-77.json', JSON.stringify(data, null, 2));
        EOF

    - name: Run encryption script
      run: node encrypt.js

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add docs/encrypted-77.json
        git commit -m 'Update encrypted JSON'
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy to GitHub Pages
      if: success()  # Only run if the previous steps were successful
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
